### ISSUE TITLE
Reading Existing Zarr Data

### ISSUE THREAD

**Issue by ilan-gold** [earth-mover/icechunk#294]
Hello all! Very Cool!

I am curious if it is possible to read existing zarr stores?  For example:

```python

import zarr
from icechunk import IcechunkStore, StorageConfig

g = zarr.open("foo.zarr", mode="w")
a = g.create_array('var', shape=(4, 4))
a[:] = np.arange(0, 16).reshape((4, 4))
g = zarr.open("foo.zarr", mode="r")
g['var'][...]

# array([[ 0.,  1.,  2.,  3.],
#        [ 4.,  5.,  6.,  7.],
#        [ 8.,  9., 10., 11.],
#        [12., 13., 14., 15.]])

storage = StorageConfig.filesystem("foo.zarr")
store = await IcechunkStore.open(storage=storage, mode='r')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[45], line 1
----> 1 store = await IcechunkStore.open(storage=storage, mode='r')

File ~/Projects/Theis/muon/venv/lib/python3.12/site-packages/icechunk/__init__.py:45, in IcechunkStore.open(cls, *args, **kwargs)
     39 @classmethod
     40 async def open(cls, *args: Any, **kwargs: Any) -> Self:
     41     """This method is called by zarr-python, it's not intended for users.
     42
     43     Use one of `IcechunkStore.open_existing`, `IcechunkStore.create` or `IcechunkStore.open_or_create` instead.
     44     """
---> 45     return cls.open_or_create(*args, **kwargs)

File ~/Projects/Theis/muon/venv/lib/python3.12/site-packages/icechunk/__init__.py:64, in IcechunkStore.open_or_create(cls, *args, **kwargs)
     62 match mode:
     63     case "r" | "r+":
---> 64         store = cls.open_existing(storage, mode, *args, **kwargs)
     65     case "a":
     66         if pyicechunk_store_exists(storage):

File ~/Projects/Theis/muon/venv/lib/python3.12/site-packages/icechunk/__init__.py:142, in IcechunkStore.open_existing(cls, storage, mode, config, *args, **kwargs)
    139         raise e
    140     else:
    141         # if the repo doesn't exists, we want to point users to that issue instead
--> 142         raise ValueError("No Icechunk repository at the provided location, try opening in create mode or changing the location") from None
    143 return cls(store=store, mode=mode, args=args, kwargs=kwargs)

ValueError: No Icechunk repository at the provided location, try opening in create mode or changing the location
```

Am I doing something wrong?  Is there appetite for this? Perhaps a contribution?

**Comment by paraseba** [comment]
Hello and thank you @ilan-gold. I see two things that are a problem with the code:
* You should use `open_existing` instead of `open`. The later is a Zarr method and it's not the intended way in which users should open their Icechunk stores.
* But changing that, your code will sill fail. Icechunk can only read data that was written using an Icechunk store.

This limitation is by design. Icechunk functional and performance advantages are derived from the way it writes its data to disk, if we try to read data written by other Zarr stores, we'll lose the features (transactionality, snapshotting, time travel, inexpensive structural changes) and, probably, most of the performance advantages.

We think reading from existing Zarr stores is well served by zarr-python (and other zarr implementations), we don't intend at this time to maintain an alternative mechanism, compatible with other stores on-disk format. We need to focus our efforts in providing a format that can do more and faster, and we are wiling to pay the price of losing compatibility.

Thank you very much for your interest, and let us know if you have other questions or interests, there is definitely other areas where we encourage contributions.

**Comment by rabernat** [comment]
One thing we could do is translate an existing Zarr store to a "virtual" Icechunk store, as we do for NetCDF. Then it could be read with Icechunk. (Arraylake already can do this: https://docs.earthmover.io/arraylake/virtual-datasets#zarr-v2)
