### ISSUE TITLE
New python API - design document

### ISSUE THREAD

**Issue by paraseba** [earth-mover/icechunk#422]
## New Icechunk Python API design

The following is pseudo-code of how a new Python API may look.

### Modules

We have different modules for sync and async interfaces. Most zarr users are not used to async
programming, so moving all async methods to a different module optimizes for clarity for the average user.

```python
import icechunk.sync
import icechunk.async
import zarr
```

We should evaluate making `icechunk.sync` just `icechunk`, or some type of alias.

### Free functions

```python
import icechunk.sync as icechunk

# TODO: define the types for arguments and return values for these functions
#       in a way that works for all configurations and object stores

storage = .....
icechunk.exists(storage)
repo: Repository = icechunk.create_repository(storage, ...)
repo: Repository = icechunk.open(storage, ...)
repo: Repository = icechunk.open_or_create(storage, ...)
```

Notice, there is no way to instantiate `Repository` in read only mode. This is by design, it would make the API more complex for very little value. As we'll see there is the concept of `Session` that can in fact be read-only.

### Ancestry data structures

```python
@dataclasss
class Commit
  msg: str
  created_at: datetime
  snapshot_id: str
```

### Repo management

Once we open a `Repository` by calling `open`,  `create_repository` or `open_or_create`, we can inspect it and manage it.

```python
import icechunk.sync as icechunk

repo = icechunk.open(...)

# exception if snapshot not found
repo.create_branch("dev", "some-snapshot-id")
# exception if snapshot not found
repo.reset_branch("dev", "some-snapshot-id")

# exception if snapshot not found
repo.create_tag("v1.0.5", "some-snapshot-id")

# returns the sequence of parent commits including some-snapshot-id
# exception if snapshot not found
repo.ancestry("some-snapshot-id") -> Iterator[Commit]

# returns branch names
repo.list_branches() -> Iterator[str]

# returns tag names
repo.list_tags() -> Iterator[str]

# returns the snapshot id pointed by a ref
# exception if ref not found
repo.get_ref(branch="main") -> str
repo.get_ref(tag="v1.0.5") -> str
```

### Read only sessions

Having a `Repository` instance allows the creation of read sessions. These are created using the `read_session` method, and they resolve to a snapshot id at the time of creation. If a branch is reset afterwards, or a tag deleted, the session doesn't change.

```python
import icechunk.sync as icechunk

repo = icechunk.open(...)
# exception if branch/tag/snapshot cannot be found
session = repo.read_session(branch="main")
session = repo.read_session(tag="v1")
session = repo.read_session(snapshot="abcde")

session.ancestry() -> Iterator[Commit]
session.snapshot_id -> str

# Should the session implement a zarr store directly instead?
root = zarr.group(store=session.store)
```

### Write sessions with manual commit

```python
import icechunk.sync as icechunk

repo = icechunk.open(...)

session = repo.write_session("main", "optional commit message")
session.describe("change the commit message")
session.description -> str | None

root = zarr.group(store=session.store)
group = root.create_group("group1")

session.commit() -> "some-snapshot-id" # the commit message can be passed here too
# calls to any session methods will fail after this, with an exception indicating the session is closed

# instead of committing user can also do
session.abandon()
# calls to any session methods will fail after this, with an exception indicating the session is closed
```

### Dangling write sessions

Expert users may want to create new snapshots that are not tracked by any refs. These are, of course, targets for garbage collection, but this property makes them useful for quick tests, experiments and debugging sessions.

```python
import icechunk.sync as icechunk

repo = icechunk.open(...)

session = repo.dangling_session("some-snapshot-id")

root = zarr.group(store=session.store)
group = root.create_group("group1")

session.commit() -> "some-snapshot-id" # the commit message can be passed here too
```

### Write sessions with manual commit and rebase

```python
import icechunk.sync as icechunk

repo = icechunk.open(...)

session = repo.write_session("main", "optional commit message")
try:
  store.commit("create group")
except Conflict as e:
  e.expected_parent -> str | None
  e.actual_parent -> str | None
  # TODO: we need a way to log conflicts
  session.rebase(BasicConflictSolver())
  session.commit("create group")
```

### Write sessions with automatic commit and optional rebase

Sessions used as context managers commit when the context finishes.

```python
with repo.write_session("main", "create group", rebase_with=BasicConflictSolver()) as session:
  session.describe(session.description + " - automatic commit")
  root = zarr.group(store=session.store)
  group = root.create_group("group1")
```

### Distributed writes

TODO

**Comment by paraseba** [comment]
We should add here a way to obtain the nodes from a `Session`

**Comment by rabernat** [comment]
This is super important stuff Seba. Thanks for getting the conversation started.

Here are some comments.

- General design
  - I really like the separation between `Repository`, `Session`, and `Store`.
  - I like separate modules from sync and async, rather than mixing them in a single class
- Repository object
  - There are going to be repos that are, in practice, read-only--for example, if the user doesn't have write permissions. With your proposal that "there is no way to instantiate Repository in read only mode," what would happen if a user tries to create a branch? A runtime error? 
  - Is this where you imagine GC and other maintenance functions eventually living?
- Session
  - Overall I like it. There's a reason we have this in Arraylake.
  - `sesion.store` is exactly where I think the Zarr store should live
  - It may be inconvenient that the session expires after it is committed. (For example, this would break some existing demos.) But on consideration, I think this is for the best. There may be mutable Zarr objects floating around still associated with that session. Under this new model, it would be impossible to write to them--they would need to be re-instantiated. I think that's the right move. For example, it would be impossible to do (pseudocode)
    ```python
    array = zarr.open(session.store, path="myarray")
    array[:] = 1
    session.commit()
    array[:] = 2  # would error
    ```
    Instead, the array would have to be re-opened after every commit. Are we okay with this? I think so, but worth discussing.
   - I _really like_ the session context manager. This is clearly the right pattern for transactions. The only downside is that it may not play well in a distributed write context.
- Dangling Write Sessions - I'm not a fan! Isn't this what branches are for? Let's encourage users to create branches liberally.
- Rebase API. I really like where you're heading, but I think this API design needs its own dedicated design doc. I'd want to see a lot more examples. Let's first agree on the high-level structure.

**Comment by mpiannucci** [comment]
> Repo management

This whole section looks perfect to me. I strongly support making store represent just the zarr store part of the current API. 

I also think the rust should follow the same convention, where a `Repository` is the entry point and the `Store` is obtained from the `Repository` instance. This will make it easier to make storage and settings dynamic. 

> Read only sessions

What is the distinction between a `session` and a `store`? I don't really understand why we need sessions in the first place, so its mostly a context thing on my part.

**Comment by mpiannucci** [comment]
> Instead, the array would have to be re-opened after every commit. Are we okay with this? I think so, but worth discussing.

This seems liek super bad UX to me personally. but maybe i dont understand how it fits into others workflows

**Comment by paraseba** [comment]
@mpiannucci great feedback, some responses inline:

> What is the distinction between a session and a store?

Great question. There is not a big difference, but the session could one day do more than the store. For example, we could add callbacks when sessions are created/finished; we could make the sessions persistent (and recoverable); we could add "attributes" like author, process, etc.

> thinking about other ACID databases, you are not expected to get a new client after every commit typically

I think of sessions as transactions actually. In fact, that was my initial name for them. Creating a new session must be mostly a NOOP, very very cheap. All the caching happens at the Repository level.

**Comment by mpiannucci** [comment]
OK I think I am understanding this better. The repository is not checked out to any given ref, instead you create sessions that point at a ref.

**Comment by mpiannucci** [comment]
Some final notes before implementing: 

* Rust will now have the `Repository`, `Session`, and `Store`
* The python implementation with follow the rust implementation as closely as possible
* Users will always open or create a `Repository`, from which the storage is passed down to sessions. 
* Sessions and Stores will require being serializable in order to allow for distributed workloads in python. 

Questions:
* Should we create two different session interfaces, one for Readable and one for Writeable ? Or just one interface with a read_only flag? This would probably mean implementing a trait inheritance where `WriteableSession: ReadableSession` or something like that

**Comment by paraseba** [comment]
> Should we create two different session interfaces, one for Readable and one for Writeable 

I think i like that approach, unless you see any complications.
